### ISSUE TITLE
WiiSX Full Base WAD shows Error 004

### ISSUE THREAD

**Issue by GabubuAvailable** [Brawl345/customizemii#71]
https://user-images.githubusercontent.com/88589756/133883190-03d4cc47-d8a2-4efd-8930-652821700c2c.mp4

Here is the error.
If you want to test it, please... PLEASE TEST IT FIRST ON DOLPHIN...

**Comment by Brawl345** [comment]
That's kinda funny. Thanks for the report though, maybe someone could test it on console with Priiloader. I won't/can't fix this but I will pin the warning.

**Comment by emilydaemon** [comment]
Tested the WAD on 4.3E and 3.1E. On 4.3E, I get the 004 error, but on 3.1E, the WAD doesn't give me the error.

**Comment by GabubuAvailable** [comment]
UPDATE: I recreated the WiiSX forwarder. So, that means, no Error 004 during the animation. Here is the video if you want to see how it looks. If you want to upload my forwarder, feel free to do that
https://youtu.be/abYOLKt3IAQ
